### ISSUE TITLE
Unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by jwoodhouse** [grafana-toolbox/grafana-wtf#150]
Using both:

`grafana-wtf explore datasources` and `grafana-wtf explore dashboards` in our environment causes this to happen:

```
Traceback (most recent call last):
    File "/home/admin/.local/bin/grafana-wtf", line 8, in <module>
        sys.exit(run())
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/commands.py", line 322, in run
        results = engine.explore_dashboards(with_data_details=options.data_details, queries_only=options.queries_only)
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/core.py", line 482, in explore_dashboards
        ix = Indexer(engine=self)
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/core.py", line 613, in __init__
        self.index()
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/core.py", line 617, in index
        self.index_dashboards()
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/core.py", line 680, in index_dashboards
        item = DatasourceItem.from_payload(item)
    File "/home/admin/.local/lib/python3.10/site-packages/grafana_wtf/model.py", line 177, in from_payload
        return cls(**payload)
TypeError: DatasourceItem.__init__() got an unexpected keyword argument 'default'
```

Grafana version `10.2.3`

Our instance of Grafana has in the thousands of dashboards, so its unfortunately not feasible for me to find the specific one causing this issue, in order to post the JSON structure. This must have been a somewhat recent dashboard addition that caused this, as ~2 weeks ago this was working fine with no grafana-wtf version change.

As a quick fix on my end I was able to update the DatasourceItem class here: https://github.com/grafana-toolbox/grafana-wtf/blob/da9232829ed0179cf256ed99471851a406cf1d95/grafana_wtf/model.py#L161-L170

with an extra argument:
`default: Optional[str] = None`

**Comment by amotl** [comment]
Hi @jwoodhouse. Thanks for your excellent report and instructions how to work around the problem. Would you be up for submitting a corresponding patch? We will be happy to converge that improvement into another release right away. Cheers.

**Comment by sanadhis** [comment]
Hey @jwoodhouse your workaround above also works for my setting:
- grafana-wtf v0.20.0
- grafana (cloud): 11.4.0-79146

Would be happy to see this being patched 😄

**Comment by jwoodhouse** [comment]
Glad to hear its helped you as well. I've been a bit busy recently, but I'll dedicate some time this weekend to submit a PR with a patch.

**Comment by rlauzon-ea** [comment]
hi @jwoodhouse, thank you for the fix! Did you have a chance to work on the bug patch?

**Comment by amotl** [comment]
Hi. I've submitted a patch per GH-160. Can you check if it's correct?

**Comment by amotl** [comment]
Hi. [Version 0.20.2](https://github.com/grafana-toolbox/grafana-wtf/releases/tag/0.20.2), just released, includes your fix. Please report back if that new release will resolve the issue for you. Thanks again for your contribution.

**Comment by sanadhis** [comment]
hi @amotl I have tried version 0.20.2 and it works like a charm.
Thanks for this!

**Comment by rlauzon-ea** [comment]
Thank you @amotl for the fix! it is working for me too.

**Comment by amotl** [comment]
Thanks for your feedback. Closing this.
